### PR TITLE
LogisticRegression for ecoli dataset

### PR DESCRIPTION
**Pull request by zairah10**
Performed Logistic regression on ecoli dataset and tweaked the two parameters (C and penalty).

### CODE REVIEW

**Comment by rhiever** [comment]
@zairah10 / @AkshayVarik: I don't see the code that you're using for saving the results to a file. Can you please commit that code? Everything seems to be running fine for me.

BTW: If you're not using the IPython Notebook (although I highly recommend using it), the file format you should use is `.py`, e.g., `LogisticRegression.py` for the file you committed yesterday.

**Comment by zairah10** [comment]
Hi Randy, since we were facing problems in saving the ouput file, we just copied the results in an excel sheet. And we used IPython (Jupyter) only for the codes that we committed yesterday.

**Comment by rhiever** [comment]
I see. Can you please commit (or paste the code here) that produces the error, along with the full error message? We can try to clear this issue up at our meeting next week, since it won't be scalable to copy-and-paste the results into Excel spreadsheets in the long-term.

In the meantime, focus on coding up all of the classifiers that we're looking into along with their parameters.

**Comment by AkshayVarik** [comment]
Hi Randy

The code that produces the error is this (Its the same one that you wrote
in the Basic Parameter Sweep example). Yes we definitely need to get over
the trouble in order to be able to systematically save our work in the
future. And both me and Zairah are focusing our attention towards getting
the code for all the algorithms with the parameter mentioned in the
document readied.


import os
import gzip

if not os.path.isdir('benchmark_results'):
    os.mkdir('benchmark_results')

with
gzip.open('benchmark_results/DecisionTreeClassifier-benchmarks.tsv.gz',
'w') as out_file:
    header_text = '\t'.join(['dataset',
                              'model',
                              'parameters',
                              'testing_score']) + '\n'
    out_file.write(header_text.encode('UTF-8'))

    for (dataset, model, params) in all_model_scores:
        param_string = ''
        param_string += 'max_depth={},'.format(params[0])
        param_string += 'max_features={},'.format(params[1])
        param_string += 'criterion={}'.format(params[2])

        for testing_score in all_model_scores[(dataset, model, params)]:
            out_text = '\t'.join([dataset[5:-7],
                                  model,
                                  param_string,
                                  str(testing_score)]) + '\n'
            out_file.write(out_text.encode('UTF-8'))


Thanks

On Sat, Feb 13, 2016 at 5:15 PM, Randy Olson <notifications@github.com>
wrote:

> I see. Can you please commit (or paste the code here) that produces the
> error, along with the full error message? We can try to clear this issue up
> at our meeting next week, since it won't be scalable to copy-and-paste the
> results into Excel spreadsheets in the long-term.
>
> In the meantime, focus on coding up all of the classifiers that we're
> looking into along with their parameters.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/sklearn-benchmarks/pull/3#issuecomment-183765275>
> .
>



-- 
Akshay Varik
Graduate Student- Batch of 2016
Department of Mechanical Engineering and Applied Mechanics
University of Pennsylvania, Philadelphia, PA 19104
Ph: +1 (267) 269 0244

**Comment by rhiever** [comment]
One thing that may be worth trying is changing this line:

```python
with gzip.open('benchmark_results/DecisionTreeClassifier-benchmarks.tsv.gz', 'w') as out_file:
```

to

```python
with gzip.open('benchmark_results/DecisionTreeClassifier-benchmarks.tsv.gz', 'wb') as out_file:
```

Let me know if that works. Without seeing the specific errors you're encountering, it is difficult to debug the issue. If you can find the specific errors that are occurring, then we can look more closely at the issue.

**Comment by AkshayVarik** [comment]
Hey Randy

The error persists. And what exactly is the console? I tried to look up
online to see when I can get  ore info of the error. I downloaded the
console to which I have access on the anaconda prompt. But havent been able
to figure out how to get the details of the error as yet.

On Sat, Feb 13, 2016 at 5:31 PM, Randy Olson <notifications@github.com>
wrote:

> One thing that may be worth trying is changing this line:
>
> with gzip.open('benchmark_results/DecisionTreeClassifier-benchmarks.tsv.gz', 'w') as out_file:
>
> to
>
> with gzip.open('benchmark_results/DecisionTreeClassifier-benchmarks.tsv.gz', 'wb') as out_file:
>
> Let me know if that works. Without seeing the specific errors you're
> encountering, it is difficult to debug the issue. If you can find the
> specific errors that are occurring, then we can look more closely at the
> issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rhiever/sklearn-benchmarks/pull/3#issuecomment-183766447>
> .
>



-- 
Akshay Varik
Graduate Student- Batch of 2016
Department of Mechanical Engineering and Applied Mechanics
University of Pennsylvania, Philadelphia, PA 19104
Ph: +1 (267) 269 0244

**Comment by rhiever** [comment]
How are you running the script currently? Do you run it on the command line (say, in cygwin?) with `python [SCRIPT NAME]`?

**Pull request closed without merging**
